repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.7.0
    hooks:
      - id: black

# Local hook to prevent committing alembic/tmp_alembic.ini
  - repo: local
    hooks:
      - id: block-tmp-alembic
        name: Prevent committing alembic/tmp_alembic.ini
        entry: bash -c 'if git diff --cached --name-only | grep -q "^alembic/tmp_alembic.ini$"; then echo "Error: attempt to commit alembic/tmp_alembic.ini"; exit 1; fi'
        language: script
        files: ''
